Добавил Flex ы страници каталога, изменил катрочки
htmlacademy-htmlcss/2196291-sedona-35 pull request #6
Opened 2022-10-15 16:14 UTC by ESemenoB

2022-10-17 08:07 UTC, craz3r requested changes

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +  box-shadow: none none 15px rgba(0, 0, 0, 0.2);
Лучше писать так как было в предыдущей версии кода, box-shadow: 0 0 15px ...

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +  justify-content: space-between;
Не лучший выбор для этого блока использовать space-between, тк почти невозможно правильно регулировать отступы между элементами. Безопасно space-between можно использовать в случаях, когда флекс контейнер тянется на всю ширину страницы или контентной зоны и не предполагает переносов

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +  justify-content: space-between;
То же самое и тут

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +  justify-content: space-between;
Лучше переделать на flex-start и вручную добавить маргинов элементам, или использовать свойство gap

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +  justify-content: space-between;
Тут тоже необязательно space-between

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +  justify-content: space-between;
Вот что бывает если использовать space-between неосторожно)
Я добавил лишний элемент в список
<img width="976" alt="Screenshot 2022-10-17 at 11 04 04" src="https://user-images.githubusercontent.com/12268931/196122478-076d21eb-acda-4f1f-ab99-09b9dfbdeaed.png">

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +.Subscribe {
Классы должны быть написаны с маленькой буквы

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +.Subscribe-box {
Классы должны быть написаны с маленькой буквы

2022-10-17 08:07 UTC, craz3r commented on styles/styles.css
> +.Subscribe-index {
Классы должны быть написаны с маленькой буквы

2022-10-17 16:03 UTC, ESemenoB commented on styles/styles.css
> +  justify-content: space-between;
Поправил!

2022-10-18 16:01 UTC, ESemenoB commented on styles/styles.css
> +  justify-content: space-between;
с трудом но переделал.

2022-10-18 16:54 UTC, ESemenoB commented on styles/styles.css
> +  justify-content: space-between;
поправил! Но лучше проверь!

2022-10-18 17:28 UTC, ESemenoB commented on styles/styles.css
> +  justify-content: space-between;
ну и тут тоже проверяй!!!

2022-10-19 07:39 UTC, merged